name: gotiny
adopt-info: gotiny
summary: GoTiny URL shortener for your terminal
description: |
  Fast:  
  GoTiny is stripped down to just the bare minimals for extremely fast performance. 
  With an average processing time of just ~34ms, nothing comes between you and long URLs.
  
  Secure:
  Privacy is important. GoTiny does not handle, collect or store any user information. 

  Accessible:
  You get a short link! You get a short link! Everybody gets a short link! 
  
license: MIT

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

apps:
  gotiny:
    command: gotiny
    extensions:
      - gnome
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - network
      - browser-support
      
parts:
  gotiny:
    source: https://github.com/kz6fittycent/gotiny-snap
    source-type: git
    plugin: nil    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
    stage-packages:
      - zenity 
      
  launcher:
    plugin: dump
    source: scripts
